name: Backend - Deploy to GCP

on:
  workflow_dispatch:
  # Trigger the workflow on pushes to the main branch, including PR merges:
  push:
    branches:
      - main

# Generate a GitHub token that can be exchanged with Google Cloud - see
# https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
permissions:
  contents: read
  id-token: write
  deployments: write

jobs:
  cloud-run: 
    name: GCP Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          workload_identity_provider: projects/28604544957/locations/global/workloadIdentityPools/paqueteria-martinez-st-louis/providers/github
          service_account: paqueteria-martinez-st-louis@paqueteria-martinez-st-louis.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.0.0

      - name: Authorize push to Google Cloud Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t us-central1-docker.pkg.dev/paqueteria-martinez-st-louis/product-assistant/product-assistant-backend:latest ./product-assistant-backend

      - name: Push Docker Image to Artifact Registry
        run: docker push us-central1-docker.pkg.dev/paqueteria-martinez-st-louis/product-assistant/product-assistant-backend:latest

      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          region: us-central1
          service: product-assistant-backend
          image: us-central1-docker.pkg.dev/paqueteria-martinez-st-louis/product-assistant/product-assistant-backend:latest
          secrets: |
            GOOGLE_API_KEY=product-assistant-ai-google-api-key:latest
            CHROMA_API_TOKEN=product-assistant-ai-chroma-api-token:latest
            CHROMA_TENANT=product-assistant-ai-chroma-tenant:latest
            CHROMA_DATABASE=product-assistant-ai-chroma-database:latest
            CHROMA_COLLECTION=product-assistant-ai-chroma-collection:latest
          env_vars: |
            DOMAIN_URL=https://paqueteria-martinez-production-6yim6fxlza-uc.a.run.app
          flags: |-
            --port 8000
            --cpu=1
            --memory=512Mi
            --allow-unauthenticated
            --platform managed
            --min-instances 0
            --service-account paqueteria-martinez-st-louis@paqueteria-martinez-st-louis.iam.gserviceaccount.com
